# Generated by Django 2.2 on 2020-02-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200204_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='data_model_file',
            new_name='data_set_file',
        ),
    ]
