# Generated by Django 2.2 on 2020-02-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200204_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='data_set_description',
            new_name='dataset_description',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='data_set_file',
            new_name='dataset_file',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='data_set_name',
            new_name='dataset_name',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='data_set_url',
            new_name='dataset_url',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='project',
            new_name='post',
        ),
    ]
