# Generated by Django 2.2 on 2020-02-04 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200204_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataSetDetails', to='blog.Post'),
        ),
    ]
