# Generated by Django 2.2 on 2020-02-05 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200204_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlModelDetails', to='blog.Post'),
        ),
    ]
