# Generated by Django 2.2 on 2020-02-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200205_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='post',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='dlmodel',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RemoveField(
            model_name='performancemetrics',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='accuracy_or_utilization',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performanceDetails', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='task',
            field=models.CharField(max_length=900),
        ),
    ]
