# Generated by Django 2.2 on 2020-02-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200214_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='dlmodel',
            old_name='project_id',
            new_name='project',
        ),
    ]
