# Generated by Django 2.2 on 2020-02-17 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_decription', models.TextField(blank=True, null=True)),
                ('task', models.CharField(max_length=900)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('configurations_varied', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_time', models.FloatField(blank=True, null=True)),
                ('testing_time', models.FloatField(blank=True, null=True)),
                ('accuracy_or_utilization', models.FloatField()),
                ('metrics_description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performanceDetails', to='dlBench.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_framework', models.CharField(max_length=100)),
                ('model_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='DL_Model_Files')),
                ('model_description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlModelDetails', to='dlBench.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=300)),
                ('dataset_url', models.URLField(blank=True, max_length=1000)),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to='Data_Set_Files')),
                ('dataset_description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataSetDetails', to='dlBench.Project')),
            ],
        ),
    ]
