# Generated by Django 2.2 on 2020-02-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlBench', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_decription',
            new_name='project_description',
        ),
    ]
